const projectAttributes = [
  {
    id: 'seeProjectTonicBtn',
    src: 'images/rock-paper-scissors.png',
    title: 'Image 0',
    alt: 'Screenshot of the Rock paper scissors project',
    mdDescription: 'Enjoy rounds of rock paper scissors game',
    smDescription: 'Rock paper scissors',
    tagLi: ['Ruby on rails', 'Css', 'JavaScript', 'html'],
    btnHrefFirst: 'https://odin-project-rock-paper-scissors.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/odin-project-rock-paper-scissors',
  },
  {
    id: 'seeProjectTonicTwoBtn',
    src: 'images/random-password-gen.png',
    title: 'Image 1',
    alt: 'Screenshot of random generator app project',
    mdDescription: 'Generates new passwords for just you',
    smDescription: 'Random password generator',
    tagLi: ['C++', 'Ruby', 'Python', 'Jquery'],
    btnHrefFirst: 'random-pasword-gen.netlify.app',
    btnHrefSecond: 'https://github.com/Yinkusadel/random-password-generator',
  },
  {
    id: 'multiPostPopup',
    src: 'images/basketball-scoreboard.png',
    title: 'Image 2',
    alt: 'Screenshot of the basketball scoreboard project',
    mdDescription: 'You got days few days off mon tue wed',
    smDescription: 'Basketball scoreboard',
    tagLi: ['Ember', 'Spring', 'Django', 'Vue'],
    btnHrefFirst: 'https://basketballs-score-board.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/basketball-scoreboard',
  },
  {
    id: 'multiPostTwoPopup',
    src: 'images/calculator-app.png',
    title: 'Image 3',
    alt: 'Screenshot of the calculator app project',
    mdDescription: 'Explore art on a whole new level',
    smDescription: 'Javascript calculator app',
    tagLi: ['Laravel', 'Angular', 'React', 'Express'],
    btnHrefFirst: 'https://adels-calculator-app.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/adel-js-calculator-app',
  },
  {
    id: 'faceBookPopup',
    src: 'images/building-blackjack.png',
    title: 'Image 4',
    alt: 'Screenshot of the building blackjack project',
    mdDescription: 'Exploring the future of media ',
    smDescription: 'Building blackjack0',
    tagLi: ['Symfony4', 'Codeigniter', 'Backbone', 'Flask'],
    btnHrefFirst: 'https://scrimba-building-blackjack.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/scrimba-building-blackjack',
  },
  {
    id: 'naturePopup',
    src: 'images/passengercounter.png',
    title: 'Image 5',
    alt: 'Screenshot of the passenger counter project',
    mdDescription: 'All about nature and temperature ',
    smDescription: 'Passenger counter App',
    tagLi: ['Svelte', 'Css', 'Software framework', 'Asp.net'],
    btnHrefFirst: 'https://scrimba-passengercounter-app.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/scrimba-passenger-counter-app',
  },
];

export default projectAttributes;
