const projectAttributes = [
  {
    id: 'seeProjectTonicBtn',
    src: 'images/rock-paper-scissors.png',
    title: 'Image 0',
    alt: 'Image 0 Alt Text',
    mdDescription: 'Enjoy rounds of rock paper scissors game',
    smDescription: 'Rock paper scissors',
    tagLi: ['Ruby on rails', 'Css', 'JavaScript', 'html'],
    btnHrefFirst: 'https://deploy-preview-1--odin-project-rock-paper-scissors.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/odin-project-rock-paper-scissors/pull/1',
    class: 'tonic-popup',
    popupNavPrevious: `popup-nav-previous`,
    popupNavNext: `popup-nav-next`,
  },
  {
    id: 'seeProjectTonicTwoBtn',
    src: 'images/random-password-gen.png',
    title: 'Image 1',
    alt: 'Image 1 Alt Text',
    mdDescription: 'Generates new passwords for just you',
    smDescription: 'Random password generator',
    tagLi: ['C++', 'Ruby', 'Python', 'Jquery'],
    btnHrefFirst: 'https://deploy-preview-1--random-pasword-gen.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/random-password-generator/pull/1',
    class: 'tonic-two-popup',
    popupNavPrevious: `popup-nav-previous`,
    popupNavNext: `popup-nav-next`,
  },
  {
    id: 'multiPostPopup',
    src: 'images/basketball-scoreboard.png',
    title: 'Image 2',
    alt: 'Image 2 Alt Text',
    mdDescription: 'You got days few days off mon tue wed',
    smDescription: 'Basketball scoreboard',
    tagLi: ['Ember', 'Spring', 'Django', 'Vue'],
    btnHrefFirst: 'https://deploy-preview-1--basketballs-score-board.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/basketball-scoreboard/pull/1',
    class: 'multipost-popup',
    popupNavPrevious: `popup-nav-previous`,
    popupNavNext: `popup-nav-next`,
  },
  {
    id: 'multiPostTwoPopup',
    src: 'images/calculator-app.png',
    title: 'Image 3',
    alt: 'Image 3 Alt Text',
    mdDescription: 'Explore art on a whole new level',
    smDescription: 'Javascript calculator app',
    tagLi: ['Laravel', 'Angular', 'React', 'Express'],
    btnHrefFirst: 'https://deploy-preview-6--adels-calculator-app.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/adel-js-calculator-app/pull/6',
    class: 'multipost-two-popup',
    popupNavPrevious: `popup-nav-previous`,
    popupNavNext: `popup-nav-next`,
  },
  {
    id: 'faceBookPopup',
    src: 'images/building-blackjack.png',
    title: 'Image 4',
    alt: 'Image 4 Alt Text',
    mdDescription: 'Exploring the future of media ',
    smDescription: 'Building blackjack0',
    tagLi: ['Symfony4', 'Codeigniter', 'Backbone', 'Flask'],
    btnHrefFirst: 'https://deploy-preview-1--scrimba-building-blackjack.netlify.app/',
    btnHrefSecond: 'https://github.com/Yinkusadel/scrimba-building-blackjack/pull/1',
    class: 'facebook-popup',
    popupNavPrevious: `popup-nav-previous`,
    popupNavNext: `popup-nav-next`,
  },
  {
    id: 'naturePopup',
    src: 'images/passengercounter.png',
    title: 'Image 5',
    alt: 'Image 5 Alt Text',
    mdDescription: 'All about nature and temperature ',
    smDescription: 'Passenger counter App',
    tagLi: ['Svelte', 'Css', 'Software framework', 'Asp.net'],
    btnHrefFirst: 'https://deploy-preview-1--scrimba-passengercounter-app.netlify.app',
    btnHrefSecond: 'https://github.com/Yinkusadel/scrimba-passenger-counter-app/pull/1',
    class: 'nature-popup',
    popupNavPrevious: `popup-nav-previous`,
    popupNavNext: `popup-nav-next`,
  },
];

export default projectAttributes;
